version: '3.8'
services:
  clickhouse:
    image: clickhouse/clickhouse-server:25.5-alpine
    environment:
      CLICKHOUSE_USER: ${DB_USER}
      CLICKHOUSE_PASSWORD: ${DB_PASSWORD}
      CLICKHOUSE_DB: ${DB_NAME}
    ports:
      - '8123:8123'
      - '9000:9000'
    volumes:
      - clickhouse_data:/var/lib/clickhouse
      - clickhouse_log:/var/log/clickhouse-server
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    healthcheck:
      test: ["CMD-SHELL", "wget --no-verbose --tries=1 --spider http://127.0.0.1:8123/ping || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s
    networks:
      - de_network


volumes:
  clickhouse_data:
  clickhouse_log:


networks:
  de_network:
    driver: bridge